### ISSUE TITLE
GDMP-Demo 4.1 version

### ISSUE THREAD

**Issue by GeorgeS2019** [j20001970/GDMP-demo#9]
It is unclear how many of the users are actually using version 3 or 4.  Could consider setup a poll? Eventually leaving 4.1 as master. 

I could build Windows for 4.1 in GDMP. However, it is unclear if this is feasible with GDMP-DEMO

Please feedback if it makes sense to link GDMP and making the download of GDMP-DEMO involving mediapipe taking long time.

Please consider distributing Windows binary and provide information that users could just download GDMP-demo  without git clone recursive and it will WORK immediately

**Comment by j20001970** [comment]
Since I'm maintaining both 3.x and 4.x of GDMP-demo, this repository does have a `3.x` branch which is currently on Godot v3.5.2, but it will a bit behind 4.x branch as things need to be backported.

Since godot-4.1 released, it would be recommended to migrate from 4.0.x to 4.1, the godot project itself between these two is mostly unchanged, (only difference I noticed is calling rendering-related methods with call_deferred.) and `4.0` branch will be removed after some time.

If you only want to try precompiled libraries, pulling GDMP submodule is not needed, as it is added for development convenience.
